### PR TITLE
Misc optimizations

### PR DESCRIPTION
**Pull request by SHiLLySiT**
The main branch has diverged a bit. I've got it running again, but I haven't figured out why the character isn't rendering.

### CODE REVIEW

**Comment by hteumeuleu** [comment]
Thank you! I'll look into this and see how I can safely merge this.

**Comment by hteumeuleu** [comment]
Alright, I don't know this hasn't been pushed here, but I remerged your changes into a branch at `pullrequests/SHiLLySiT/main` (https://github.com/hteumeuleu/celeste/tree/pullrequests/SHiLLySiT/main). There's one bug I notice in the clouds (`platform` object) levels (like `6,0`) is that the player no longer follows the movement of the platform. I'm wondering if this wouldn't be related to the update you did in the `collide` function. Do you think you could have a look?

**Comment by hteumeuleu** [comment]
Nevermind, I was able to fix this issue! I'll do a few more tests and merge things then.

**Comment by hteumeuleu** [comment]
I did the merge through pr#2 https://github.com/hteumeuleu/celeste/pull/2
Thanks again for your help!

**Comment by SHiLLySiT** [comment]
@hteumeuleu I've never been able to push to repo's on Github that I'm not an owner or member of 😔 Glad you were able to get it merged and fixed tho 🥳

**Pull request closed without merging**
